### ISSUE TITLE
Is there any way to disable this in development?

### ISSUE THREAD

**Issue by aexmachina** [kimroen/ember-cli-autoprefixer#6]
I've tried settings `browsers: process.env.NODE_ENV === 'production' ? ['last 2 versions'] : []` but the `AutoprefixerFilter` is still showing 1468ms in the Slowest Trees table.

**Comment by kimroen** [comment]
Hi there! Sorry about the late reply.

There was actually no way of doing what you're asking up to this point, because the options were dumb and were just passed straight on to Autoprefixer itself.

I added an option for it: You can pass in `enabled: false` to selectively disable Autoprefixer. There's an example kind of like you asked for in the PR for it: https://github.com/kimroen/ember-cli-autoprefixer/pull/7

I used `process.env.EMBER_ENV` though, you might need to adjust.

This is available with autoprefixer 0.4.0.

**Comment by aexmachina** [comment]
Awesome, thanks!
